name: Issue Label Notification

on:
  issues:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Debug Event
      run: echo "Event Title ${{ github.event.issue.title }}"

    - name: Send Notification to Another Repo
      uses: actions/github-script@v6.4.1  # 최신 버전 사용
      with:
        script: |
          # const issue = github.context.payload.issue;  // issue 객체 참조
          # const label = github.context.payload.label;  // label 객체 참조

          # // 객체가 정의되어 있는지 확인
          # if (!issue || !label) {
          #   throw new Error('이슈 또는 라벨 정보를 찾을 수 없습니다.');
          # }

          const issueTitle = ${{ github.event.issue.title }}
          const issueUrl = ${{ github.event.issue.html_url }}
          # const issueTitle = issue.title;
          # const issueUrl = issue.html_url;
          # const labelName = label.name;

          // 타겟 저장소에 새로운 이슈 생성
          await github.issues.create({
            owner: 'HayeongShim',  // 타겟 저장소의 소유자
            repo: 'TIL',     // 타겟 저장소 이름
            # title: `이슈 라벨 알림: ${issueTitle}`,
            # body: `라벨 "labelName이 추가되었습니다.\n원본 이슈 링크: ${issueUrl}`
            title: 'TEST',
            body: 'TEST BODY'
          });
